stages:
  - check
  - build

security-check:
  stage: check
  image:
   name: aquasec/trivy:latest
   entrypoint: [""] 
  tags:
    - sbom
  script:
  - trivy --insecure --format cyclonedx --output result.json fs .
  - curl -v -X POST -H "Content-Type: application/json" -d @result.json http://192.168.64.138:8000//v1/bomexchange
  artifacts:
    paths:
      - result.json

release:
  stage: build
  tags:
    - sbom
  image:
    name: artifactory.pte.sgre.one:443/acc-docker/runner/kaniko:latest
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
