stages:
  - check
  #- build
  - test

security-check:
  stage: check
  image:
   name: aquasec/trivy:latest
   entrypoint: [""] 
  tags:
    - sbom
  script:
  - trivy --insecure --scanners vuln --format cyclonedx --output source.json fs .
  artifacts:
    paths:
      - source.json

#build:
#  stage: build
#  image: 
#    name: aquasec/trivy:latest
#    entrypoint: [""]
#  tags:
#    - sbom
#  script:
#    - echo "Building Docker image..."
#    - docker build -t vulnerable-flask-app:0.1 .

security_scan:
  stage: test
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  tags:
    - sbom
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - trivy image --insecure --scanners vuln --format cyclonedx --output build.json vulnerable-flask/python-app:1.0.0  # Adjust registry URL as needed
  artifacts:
    paths:
      - build.json