stages:
  - check
  #- build
  - test

security-check:
  stage: check
  image:
   name: aquasec/trivy:latest
   entrypoint: [""] 
  tags:
    - sbom
  script:
  - trivy --insecure --scanners vuln --format cyclonedx --output source.json fs .
  artifacts:
    paths:
      - source.json

#build:
#  stage: build
#  image: 
#    name: aquasec/trivy:latest
#    entrypoint: [""]
#  tags:
#    - sbom
#  script:
#    - echo "Building Docker image..."
#    - docker build -t vulnerable-flask-app:0.1 .

security_scan:
  stage: test
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  tags:
    - sbom
  before_script:
    - apk add --no-cache docker-cli
    - mkdir -p /root/.docker
    - |
      cat << 'EOF' > /root/.docker/config.json
      {
        "insecure-registries": [
          "localhost:5000"
        ]
      }
      EOF
    - docker login localhost:5000
  script:
    - trivy image --insecure --scanners vuln --format cyclonedx --output build.json vulnerable-flask/python-app:1.0.0
  artifacts:
    paths:
      - build.json
