stages:
  - check
  - build

security-check:
  stage: check
  image:
   name: aquasec/trivy:latest
   entrypoint: [""] 
  tags:
    - sbom
  script:
  - trivy --insecure --format cyclonedx --output result.json fs .

release:
  stage: build
  tags:
    - sbom
  image:
    name: artifactory.pte.sgre.one:443/acc-docker/runner/kaniko:latest
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"