stages:
  - check
  - build
  - test

security-check:
  stage: check
  image:
   name: aquasec/trivy:latest
   entrypoint: [""] 
  tags:
    - sbom
  script:
  - trivy --insecure --format cyclonedx --output source.json fs .
  artifacts:
    paths:
      - source.json

security_scan:
  stage: test
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  tags:
    - sbom
  script:
    - trivy image --format cyclonedx --output build.json techiescamp/pet-clinic-app:1.0.0
  artifacts:
    paths:
      - build.json
