# File: .gitlab-ci.yml
include:
  - local: .gitlab/ci/trivy-scan.yml
  - local: .gitlab/ci/sbom-upload.yml

stages:
  - source
  - sbom_source

trivy_sbom_source:
  stage: source
  extends: .trivy_sbom_scan

sbom_upload:
  stage: sbom_source
  extends: .sbom_upload
  needs:
    - trivy_sbom_source
  variables:
    DEPENDENCY_TRACK_URL: "192.168.64.138"
    DEPENDENCY_TRACK_PORT: 8080
    DEPENDENCY_TRACK_API_KEY: "odt_VAMlX4xn0D82M1ywpxhpUr3aHgLSGSju"

#build:
#  stage: build
#  image: 
#    name: aquasec/trivy:latest
#    entrypoint: [""]
#  tags:
#    - sbom
#  script:
#    - echo "Building Docker image..."
#    - docker build -t vulnerable-flask-app:0.1 .

# security_scan:
#   stage: test
#   image: 
#     name: aquasec/trivy:latest
#     entrypoint: [""]
#   tags:
#     - sbom
#   script:
#     - trivy --insecure --scanners vuln --format cyclonedx --output build.json image sflorenz05/vulnerable-flask-app:1.0.0
#   artifacts:
#     paths:
#       - build.json
