stages:
  - check
  #- build
  - test

security-check:
  stage: check
  image:
   name: aquasec/trivy:latest
   entrypoint: [""] 
  tags:
    - sbom
  script:
  - trivy --insecure --scanners vuln --format cyclonedx --output source.json fs .
  artifacts:
    paths:
      - source.json

#build:
#  stage: build
#  image: 
#    name: aquasec/trivy:latest
#    entrypoint: [""]
#  tags:
#    - sbom
#  script:
#    - echo "Building Docker image..."
#    - docker build -t vulnerable-flask-app:0.1 .

security_scan:
  stage: test
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  tags:
    - sbom
  variables:
    DOCKER_AUTH_CONFIG: '{"insecure-registries" : ["localhost:5000"]}'  # If using local registry
  script:
    - trivy image --insecure --scanners vuln --format cyclonedx --output build.json localhost:5000/vulnerable-flask/python-app:1.0.0  # Adjust registry URL as needed
  artifacts:
    paths:
      - build.json
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock